// ============================================================================
// Bundled daily content for the pack games (Duality, Word, Mini). A
// pack day is chosen deterministically from the date, so everyone plays the
// same round on the same day with ZERO daily admin work. Later, rows in a
// `daily_minigames` table can override the pack for a given date (see
// docs/BLUEPRINT.md) - the packs stay as the always-works fallback.
// ============================================================================

import { hashSeed } from "@/lib/seed";

// --- Duality: eight definitions hide four pairs - two meanings, one word ----
// Connections-style: pairs are ordered EASY -> HARD (the four difficulty
// colors). Each pair is one word with two unrelated meanings; the player
// matches the two definitions, then the word is the reveal payoff.

export interface DualityPair {
  /** The word both definitions describe - the payoff on match. */
  word: string;
  defs: [string, string];
}

export interface DualityDay {
  pairs: DualityPair[]; // exactly 4, easiest first
}

export const DUALITY_PACK: DualityDay[] = [
  {
    pairs: [
      { word: "BANK", defs: ["Place that holds your money", "The side of a river"] },
      { word: "BAT", defs: ["Flying mammal of the night", "Swung at a baseball"] },
      { word: "JAM", defs: ["Spread made from fruit", "Cars stuck, going nowhere"] },
      { word: "NOVEL", defs: ["A long work of fiction", "Never seen before"] },
    ],
  },
  {
    pairs: [
      { word: "WAVE", defs: ["The ocean's rolling swell", "A hand saying hello"] },
      { word: "RULER", defs: ["Twelve inches of measuring", "One who wears the crown"] },
      { word: "LETTER", defs: ["One of twenty-six", "Sealed inside an envelope"] },
      { word: "CURRENT", defs: ["A river's steady pull", "Happening right now"] },
    ],
  },
  {
    pairs: [
      { word: "PARK", defs: ["Green space with benches", "Leave the car somewhere"] },
      { word: "BARK", defs: ["A dog's warning", "A tree's outer coat"] },
      { word: "PITCH", defs: ["Thrown from the mound", "How high a note sits"] },
      { word: "GRAVE", defs: ["A final resting place", "Deeply serious"] },
    ],
  },
  {
    pairs: [
      { word: "MATCH", defs: ["Strike it for fire", "A contest of equals"] },
      { word: "SEAL", defs: ["Whiskered ocean swimmer", "Close something airtight"] },
      { word: "TRUNK", defs: ["An elephant's reach", "Where the luggage goes"] },
      { word: "FAIR", defs: ["Rides and cotton candy", "Free from bias"] },
    ],
  },
  {
    pairs: [
      { word: "RING", defs: ["Worn on a finger", "The phone's cry"] },
      { word: "DATE", defs: ["A square on the calendar", "Dinner for two, maybe"] },
      { word: "BOLT", defs: ["Lightning's strike", "Take off running"] },
      { word: "STABLE", defs: ["Where horses sleep", "Not likely to tip over"] },
    ],
  },
  {
    pairs: [
      { word: "SPRING", defs: ["Coiled metal that bounces", "When the flowers return"] },
      { word: "CLUB", defs: ["A group with members", "A suit in the deck"] },
      { word: "CRANE", defs: ["Long-necked wading bird", "Lifts steel downtown"] },
      { word: "SOUND", defs: ["Anything you can hear", "Sturdy and dependable"] },
    ],
  },
];

// --- Word: one five-letter answer per day (the format you know) -------------

export const WORD_ANSWERS: string[] = [
  "CRANE", "SPORT", "MONEY", "HEART", "GLOBE", "PIZZA", "TIGER", "OCEAN",
  "MUSIC", "STORM", "BRAVE", "LIGHT", "DREAM", "TRACK", "FLAME", "CROWN",
  "PLANT", "SMILE", "RIVER", "CANDY", "SHARK", "PIANO", "GRAPE", "CLOUD",
  "STONE", "MAGIC", "TRAIN", "HONEY", "WHALE", "BREAD", "QUEEN", "LEMON",
  "SPACE", "BEACH", "NIGHT", "WATCH", "HOUSE", "SNAKE", "DANCE", "GHOST",
  "MOUNT", "TOAST", "FROST", "SOLAR", "ROBIN", "APPLE", "CHESS", "PEARL",
  "WORLD", "SCORE", "SOUND", "PAINT", "ARENA", "VOICE", "SUGAR", "EAGLE",
  "TRUTH", "OLIVE", "COACH", "MEDAL", "RANCH", "SPICE", "MAPLE", "TORCH",
  "BLAZE", "CORAL", "DERBY", "FIELD", "GIANT", "JUICE", "KNIFE", "LUNAR",
  "NOBLE", "ORBIT", "PRIZE", "QUIET", "ROAST", "SHINE", "TITAN", "VIVID",
];

// --- Selection ---------------------------------------------------------------

/** Deterministic pick: same day -> same content for every player. */
export function getDualityDaily(date: string): DualityDay {
  return DUALITY_PACK[hashSeed(`duality:${date}`) % DUALITY_PACK.length];
}

export function getWordDaily(date: string): string {
  return WORD_ANSWERS[hashSeed(`word:${date}`) % WORD_ANSWERS.length];
}

// --- Mini: a 5x5 crossword ----------------------------------------------------
// Grids are machine-verified (every across AND down entry is a real word from
// the fill dictionary; generated by backtracking, clues written by hand).
// '#' = black square. Numbering follows standard crossword rules.

export interface MiniClue {
  num: number;
  row: number;
  col: number;
  len: number;
  clue: string;
  answer: string;
}

export interface MiniDay {
  rows: string[]; // 5 strings of 5 chars, '#' for black
  across: MiniClue[];
  down: MiniClue[];
}

export const MINI_PACK: MiniDay[] = [
  {
    rows: ["SEA##", "ACRE#", "WHEAT", "#ONCE", "##AHA"],
    across: [
      { num: 1, row: 0, col: 0, len: 3, clue: "Where waves crash", answer: "SEA" },
      { num: 4, row: 1, col: 0, len: 4, clue: "Unit of farmland", answer: "ACRE" },
      { num: 6, row: 2, col: 0, len: 5, clue: "Grain in most bread", answer: "WHEAT" },
      { num: 8, row: 3, col: 1, len: 4, clue: "A single time", answer: "ONCE" },
      { num: 9, row: 4, col: 2, len: 3, clue: "Cry of discovery", answer: "AHA" },
    ],
    down: [
      { num: 1, row: 0, col: 0, len: 3, clue: "Carpenter's cutter", answer: "SAW" },
      { num: 2, row: 0, col: 1, len: 4, clue: "Canyon comeback", answer: "ECHO" },
      { num: 3, row: 0, col: 2, len: 5, clue: "Where the home team plays", answer: "ARENA" },
      { num: 5, row: 1, col: 3, len: 4, clue: "Apiece", answer: "EACH" },
      { num: 7, row: 2, col: 4, len: 3, clue: "Brit's afternoon brew", answer: "TEA" },
    ],
  },
  {
    rows: ["ART##", "SOAP#", "POLAR", "#TOGA", "##NET"],
    across: [
      { num: 1, row: 0, col: 0, len: 3, clue: "Gallery hangings", answer: "ART" },
      { num: 4, row: 1, col: 0, len: 4, clue: "Bathtub bar", answer: "SOAP" },
      { num: 6, row: 2, col: 0, len: 5, clue: "Like the Arctic, or a famous bear", answer: "POLAR" },
      { num: 8, row: 3, col: 1, len: 4, clue: "Ancient Roman wrap", answer: "TOGA" },
      { num: 9, row: 4, col: 2, len: 3, clue: "It hangs from a basketball rim", answer: "NET" },
    ],
    down: [
      { num: 1, row: 0, col: 0, len: 3, clue: "Cleopatra's snake", answer: "ASP" },
      { num: 2, row: 0, col: 1, len: 4, clue: "Cheer (for)", answer: "ROOT" },
      { num: 3, row: 0, col: 2, len: 5, clue: "Eagle's claw", answer: "TALON" },
      { num: 5, row: 1, col: 3, len: 4, clue: "One of about 300 in a novel", answer: "PAGE" },
      { num: 7, row: 2, col: 4, len: 3, clue: "Sewer scurrier", answer: "RAT" },
    ],
  },
  {
    rows: ["PET##", "OURS#", "PRIOR", "#OBOE", "##END"],
    across: [
      { num: 1, row: 0, col: 0, len: 3, clue: "Dog or cat, e.g.", answer: "PET" },
      { num: 4, row: 1, col: 0, len: 4, clue: "Belonging to us", answer: "OURS" },
      { num: 6, row: 2, col: 0, len: 5, clue: "Earlier in time", answer: "PRIOR" },
      { num: 8, row: 3, col: 1, len: 4, clue: "Reed in the orchestra", answer: "OBOE" },
      { num: 9, row: 4, col: 2, len: 3, clue: "Credits signal", answer: "END" },
    ],
    down: [
      { num: 1, row: 0, col: 0, len: 3, clue: "Soda, in the Midwest", answer: "POP" },
      { num: 2, row: 0, col: 1, len: 4, clue: "Currency in Paris", answer: "EURO" },
      { num: 3, row: 0, col: 2, len: 5, clue: "Close-knit group", answer: "TRIBE" },
      { num: 5, row: 1, col: 3, len: 4, clue: "Before long", answer: "SOON" },
      { num: 7, row: 2, col: 4, len: 3, clue: "Stop-sign shade", answer: "RED" },
    ],
  },
];

export function getMiniDaily(date: string): MiniDay {
  return MINI_PACK[hashSeed(`mini:${date}`) % MINI_PACK.length];
}
